version: "3"
services:
  back:
    container_name: back
    image: icws24submission/back_monolith
    security_opt:
      - no-new-privileges:true
    ports:
      - 5001:5001
    restart: always
    env_file:
      - variables.env
    

  postgres:
    container_name: postgres
    image: icws24submission/postgres_monolith
    restart: always
    env_file:
      - variables.env
    shm_size: 1g
  
    ports:
      - "5431:5432"
    security_opt:
      - "no-new-privileges:true"
    volumes:
      - ./v4-soy-db:/var/lib/postgresql/data

  
